fix: Remove unnecessary `??` operator
When updating to TypeScript 5.6, it now (correctly) complains:

> src/api/jobs.ts(46,20): error TS2869: Right operand of ?? is
> unreachable because the left operand is never nullish.

Hence, the unreachable code is removed.